# Generated by Django 5.1.5 on 2025-03-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_subject_note_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="pdf",
            new_name="file",
        ),
    ]
