# Generated by Django 5.1.5 on 2025-03-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_commend_options_commend_timestamp_commend_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commend",
            old_name="commend",
            new_name="message",
        ),
    ]
