# Generated by Django 5.1.5 on 2025-03-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_historicalsemester_department_semester_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsemester",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="web.department",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="web.department",
            ),
        ),
    ]
