# Generated by Django 5.1.7 on 2025-03-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department'),
        ('web', '0010_alter_historicalsemester_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.semester'),
        ),
    ]
